# Generated by Django 5.1.6 on 2025-03-01 04:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="appointmentmodel",
            table="appointments",
        ),
        migrations.AlterModelTable(
            name="customermodel",
            table="customers",
        ),
        migrations.AlterModelTable(
            name="paymentmodel",
            table="payments",
        ),
    ]
