# Generated by Django 5.1.6 on 2025-03-08 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_appointmentmodel_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='appointiment_data',
            new_name='appointment_date',
        ),
    ]
