# Generated by Django 5.1.6 on 2025-03-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_appointiment_data_appointmentmodel_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='document_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
